network: auto
metrics-enabled: true
metrics-host-allowlist: "*"
metrics-interface: "0.0.0.0"
metrics-port: "8008"
validator-keys: "/opt/charon/keys:/opt/charon/keys"
validators-graffiti: "Obol Distributed Validator"
validators-proposer-default-fee-recipient: "0x0000000000000000000000000000000000000000"
