global:
  scrape_interval:     30s # Set the scrape interval to every 12 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 12 seconds. The default is every 1 minute.

remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    authorization:
      credentials: 436764:$PROM_REMOTE_WRITE_TOKEN
    name: obol-prom
  
scrape_configs:
  - job_name: 'geth'
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['geth:6060']
  - job_name: 'lighthouse'
    static_configs:
      - targets: ['lighthouse:5054']
  - job_name: 'charon'
    static_configs:
      - targets: ['charon:3620']
  - job_name: 'teku'
    static_configs:
      - targets: ['teku:8008']   
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
