beacon-node-api-endpoint: "http://charon:3600"
metrics-enabled: true
metrics-host-allowlist: "*"
metrics-interface: "0.0.0.0"
metrics-port: "8008"
network: "prater"
validator-keys: "/opt/charon/validator_keys:/opt/charon/validator_keys"
validators-graffiti: "Obol Distributed Validator"
validators-proposer-default-fee-recipient: "0x0000000000000000000000000000000000000000"
